version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: JO_Wedding-RSVP
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Commando1+
      MYSQL_DATABASE: jo_wedding
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: wedding_rsvp
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:8000"
